DROP VIEW VW_DG_TRAVELERS_LOCATION_PREFERENCES;

DROP VIEW VW_DG_TRAVELERS_IN_GROUPS;

DROP VIEW VW_DG_TRAVELER_PREFERENCES;

DROP VIEW VW_DG_TRAVELERS_MOST_BOOKINGS;

DROP VIEW VW_DG_GROUP_DETAILS_LEADER_MEMBER;

DROP VIEW VW_DG_TRAVELERS_GROUP_BOOKINGS;

DROP VIEW VW_DG_GROUP_LEADERS_MEMBERS;

DROP VIEW VW_DG_SERVICE_PROVIDER_FULL_DETAILS;

DROP VIEW VW_DG_SERVICE_PROVIDER_AVAILABILITY_BY_LOCATION_DATE;

DROP VIEW VW_DG_SERVICE_PROVIDER_EXPERIENCES_LIST;

DROP VIEW VW_DG_MOST_BOOKED_SERVICE_PROVIDERS;

DROP VIEW VW_DG_SERVICE_PROVIDER_BY_LOCATION;

DROP VIEW VW_DG_SERVICE_PROVIDER_TOP_RATED_EXPERIENCES;

DROP VIEW VW_DG_SERVICE_PROVIDER_BOOKINGS_OVERVIEW;

DROP VIEW VW_DG_SERVICE_PROVIDER_RATINGS_FEEDBACK_OVERVIEW;

DROP VIEW VW_DG_SERVICE_PROVIDER_AVAILABILITY_SUMMARY;

DROP VIEW VW_DG_SERVICE_PROVIDER_DETAILS_WITH_ACTIVITIES;

DROP VIEW VW_DG_EXPERIENCE_DETAILS_PROVIDER_TAGS_SCHEDULE;

DROP VIEW VW_DG_EXPERIENCE_COMPLETE_DETAILS_TAGS_SCHEDULE;

DROP VIEW VW_DG_EXPERIENCE_SUMMARY_PROVIDER_LOCATION;

DROP VIEW VW_DG_EXPERIENCE_DETAILS_CONCATENATED_TAGS;

DROP VIEW VW_DG_EXPERIENCE_COUNT_BY_PRICING_RANGE;

DROP VIEW VW_DG_BOOKING_DETAILS_TRAVELER_EXPERIENCE_STATUS;

DROP VIEW VW_DG_BOOKING_PAYMENT_STATUS_TRAVELERS;

DROP VIEW VW_DG_TRAVELERS_WITH_AT_LEAST_ONE_BOOKING;

DROP VIEW VW_DG_TRAVELERS_WITH_MULTIPLE_BOOKINGS;

DROP VIEW VW_DG_TRAVELERS_WITH_NO_BOOKINGS;

DROP VIEW VW_DG_EXPERIENCES_BOOKED_BY_TRAVELER;

DROP VIEW VW_DG_SERVICE_PROVIDER_BOOKED_EXPERIENCES_COUNT;

DROP VIEW VW_DG_SERVICE_PROVIDERS_WITH_CANCELED_BOOKINGS;

DROP VIEW VW_DG_TRAVELERS_WITH_CANCELED_BOOKINGS;

DROP VIEW VW_DG_TRAVELERS_BOOKED_EXPERIENCE;

DROP VIEW VW_DG_TRAVELERS_WITH_REVIEWS;

DROP VIEW VW_DG_TRAVELERS_WITH_NO_REVIEWS;

DROP VIEW VW_DG_TRAVELER_REVIEW_DETAILS;

DROP VIEW VW_DG_SERVICE_PROVIDER_AVERAGE_RATING;

DROP VIEW VW_DG_EXPERIENCE_AVERAGE_RATING;

DROP VIEW VW_DG_TOP_RATED_EXPERIENCES_LIST;

DROP VIEW VW_DG_TOTAL_EARNINGS_CONFIRMED;

DROP VIEW VW_DG_TOTAL_REFUNDED_AMOUNT;

DROP VIEW VW_DG_SERVICE_PROVIDER_MOST_BOOKINGS;

DROP VIEW VW_DG_MONTHLY_BOOKING_VOLUME;

DROP VIEW VW_DG_TOP_LOCATIONS_AVAILABLE_EXPERIENCES;

DROP VIEW VW_DG_AVERAGE_RATING_BY_LOCATION;

DROP VIEW VW_DG_GROUP_BOOKING_ANALYSIS;

DROP VIEW VW_DG_TRAVELER_DEMOGRAPHIC_ANALYSIS;

DROP VIEW VW_DG_REFUND_RATE_ANALYSIS;

DROP VIEW VW_DG_LOCATIONS_MOST_BOOKINGS;

DROP VIEW VW_DG_HIGHEST_LOWEST_RATED_SERVICE_PROVIDERS;

DROP VIEW VW_DG_TOP_10_RATED_SERVICE_PROVIDERS;

DROP VIEW VW_DG_MOST_BOOKED_EXPERIENCES;

DROP VIEW VW_DG_TOP_10_TRAVELERS_BOOKINGS;

DROP VIEW VW_DG_AVERAGE_AMOUNT_PAID_BY_PAYMENT_STATUS;

DROP VIEW VW_DG_TOTAL_REVENUE_BY_SERVICE_PROVIDER;

DROP VIEW VW_DG_DAILY_BOOKING_VOLUME;

DROP VIEW VW_DG_GUIDE_SUPPORT_NEEDS;

DROP VIEW VW_DG_QUARTERLY_REVENUE_BREAKDOWN;

DROP VIEW VW_DG_MONTHLY_BOOKING_TRENDS;

DROP VIEW VW_DG_REPEAT_TRAVELERS_PREFERENCES;

DROP VIEW VW_DG_EXPERIENCE_DIVERSITY;

DROP VIEW VW_DG_MONTHLY_BOOKING_COUNT_BY_EXPERIENCE;

DROP VIEW VW_DG_AVG_DAYS_BETWEEN_BOOKING_EXPERIENCE;

-- Drop trigger to check review eligibility
DROP TRIGGER trg_Review_Eligibility;

-- Drop trigger to update Group_Size after a member is added
DROP TRIGGER trg_Update_Group_Size;

-- Drop trigger to prevent the group leader from being added as a regular member
DROP TRIGGER trg_Prevent_Leader_As_Member;

-- Drop trigger to prevent bookings for experience dates
DROP TRIGGER trg_Prevent_Invalid_Booking_Dates;

-- Drop trigger to prevent cancellations for past or completed bookings
DROP TRIGGER trg_Prevent_Invalid_Cancellations;

-- Drop the Dg_Ratings table
DROP TABLE Dg_Ratings CASCADE CONSTRAINTS;

-- Drop the Dg_Bookings table
DROP TABLE Dg_Bookings CASCADE CONSTRAINTS;

-- Drop the Dg_Service_Provider_Activities table
DROP TABLE Dg_Service_Provider_Activities CASCADE CONSTRAINTS;

-- Drop the Dg_Availability_Schedule table
DROP TABLE Dg_Availability_Schedule CASCADE CONSTRAINTS;

-- Drop the Dg_Schedule_Locations table
DROP TABLE Dg_Schedule_Locations CASCADE CONSTRAINTS;

-- Drop the Dg_Schedule_Times table
DROP TABLE Dg_Schedule_Times CASCADE CONSTRAINTS;

-- Drop the Dg_Service_Provider table
DROP TABLE Dg_Service_Provider CASCADE CONSTRAINTS;

-- Drop the Dg_Experience_Tags table
DROP TABLE Dg_Experience_Tags CASCADE CONSTRAINTS;

-- Drop the Dg_Experience table
DROP TABLE Dg_Experience CASCADE CONSTRAINTS;

-- Drop the Dg_Group_Members table
DROP TABLE Dg_Group_Members CASCADE CONSTRAINTS;

-- Drop the Dg_Groups table
DROP TABLE Dg_Groups CASCADE CONSTRAINTS;

-- Drop the Dg_Traveler_Preferences table
DROP TABLE Dg_Traveler_Preferences CASCADE CONSTRAINTS;

-- Drop the Dg_Traveler_Preferences table
DROP TABLE Dg_Interest_Categories CASCADE CONSTRAINTS;

-- Drop the Dg_Travelers table
DROP TABLE Dg_Travelers CASCADE CONSTRAINTS;

-- Drop the Dg_Locations table
DROP TABLE Dg_Locations CASCADE CONSTRAINTS;

-- Drop the Dg_Group_Types table
DROP TABLE Dg_Group_Types CASCADE CONSTRAINTS;

-- Drop the Dg_Tags table
DROP TABLE Dg_Tags CASCADE CONSTRAINTS;

-- Drop the Dg_Booking_Methods table
DROP TABLE Dg_Booking_Methods CASCADE CONSTRAINTS;

-- Drop the Dg_Booking_Status table
DROP TABLE Dg_Booking_Status CASCADE CONSTRAINTS;

-- Drop the Dg_Payment_Status table
DROP TABLE Dg_Payment_Status CASCADE CONSTRAINTS;

-- Clear recycle bin
PURGE RECYCLEBIN;
