-- Inserting preferences into the Dg_Interest_Categories table
INSERT ALL
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00001', 'Beach')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00002', 'Mountain')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00003', 'City Tour')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00004', 'Adventure')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00005', 'Cruise')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00006', 'Hiking')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00007', 'Cultural Experience')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00008', 'Food and Drink')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00009', 'Wildlife Safari')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00010', 'Historical Sites')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00011', 'Nightlife')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00012', 'Shopping')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00013', 'Spa and Wellness')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00014', 'Sports Events')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00015', 'Road Trip')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00016', 'Camping')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00017', 'Photography')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00018', 'Music Festival')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00019', 'Art and Craft')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00020', 'Yoga Retreat')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00021', 'Sailing')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00022', 'Desert Safari')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00023', 'Skiing')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00024', 'Scuba Diving')
    INTO Dg_Interest_Categories (Category_ID, Category_Name) VALUES ('C00025', 'Golfing')
SELECT 1 FROM DUAL;

-- Inserting multiple rows into the Dg_Locations table
INSERT ALL
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00001', 'New York')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00002', 'Los Angeles')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00003', 'Chicago')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00004', 'Houston')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00005', 'Phoenix')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00006', 'Philadelphia')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00007', 'San Antonio')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00008', 'San Diego')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00009', 'Dallas')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00010', 'San Jose')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00011', 'Austin')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00012', 'Jacksonville')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00013', 'Fort Worth')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00014', 'Columbus')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00015', 'Charlotte')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00016', 'San Francisco')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00017', 'Indianapolis')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00018', 'Seattle')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00019', 'Denver')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00020', 'Washington')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00021', 'Boston')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00022', 'El Paso')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00023', 'Nashville')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00024', 'Detroit')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00025', 'Oklahoma City')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00026', 'Portland')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00027', 'Las Vegas')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00028', 'Memphis')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00029', 'Louisville')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00030', 'Baltimore')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00031', 'Milwaukee')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00032', 'Albuquerque')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00033', 'Tucson')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00034', 'Fresno')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00035', 'Sacramento')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00036', 'Kansas City')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00037', 'Mesa')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00038', 'Atlanta')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00039', 'Omaha')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00040', 'Colorado Springs')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00041', 'Raleigh')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00042', 'Miami')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00043', 'Virginia Beach')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00044', 'Oakland')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00045', 'Minneapolis')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00046', 'Tulsa')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00047', 'Arlington')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00048', 'Tampa')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00049', 'New Orleans')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00050', 'Wichita')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00051', 'Cleveland')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00052', 'Bakersfield')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00053', 'Anaheim')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00054', 'Honolulu')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00055', 'Santa Ana')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00056', 'Riverside')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00057', 'Corpus Christi')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00058', 'Lexington')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00059', 'Henderson')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00060', 'Stockton')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00061', 'Saint Paul')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00062', 'Cincinnati')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00063', 'St. Louis')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00064', 'Pittsburgh')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00065', 'Greensboro')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00066', 'Anchorage')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00067', 'Plano')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00068', 'Lincoln')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00069', 'Orlando')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00070', 'Irvine')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00071', 'Newark')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00072', 'Durham')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00073', 'Chula Vista')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00074', 'Toledo')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00075', 'Fort Wayne')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00076', 'St. Petersburg')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00077', 'Laredo')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00078', 'Jersey City')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00079', 'Chandler')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00080', 'Madison')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00081', 'Lubbock')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00082', 'Scottsdale')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00083', 'Reno')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00084', 'Buffalo')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00085', 'Gilbert')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00086', 'Glendale')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00087', 'North Las Vegas')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00088', 'Winston-Salem')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00089', 'Chesapeake')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00090', 'Norfolk')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00091', 'Fremont')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00092', 'Garland')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00093', 'Irving')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00094', 'Hialeah')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00095', 'Richmond')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00096', 'Boise')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00097', 'Spokane')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00098', 'Baton Rouge')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00099', 'Tacoma')
    INTO Dg_Locations (Location_ID, Location_Name) VALUES ('L00100', 'Fayetteville')
SELECT 1 FROM DUAL;

-- Inserting group types into the Dg_Group_Types table
INSERT ALL
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT001', 'Family')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT002', 'Friends')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT003', 'Corporate Team')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT004', 'Adventure')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT005', 'Social')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT006', 'Fitness')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT007', 'Hiking')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT008', 'Cultural')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT009', 'Wellness')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT010', 'Photography')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT011', 'Cooking')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT012', 'Music')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT013', 'Art')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT014', 'Travel')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT015', 'Gaming')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT016', 'Volunteering')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT017', 'Outdoor')
    INTO Dg_Group_Types (Group_Type_ID, Group_Type_Name) VALUES ('GT018', 'Networking')
SELECT 1 FROM DUAL;

-- Inserting experience tags into the Dg_Tags table
INSERT ALL
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T001', 'Relaxation')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T002', 'Adventure')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T003', 'Family')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T004', 'Outdoor')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T005', 'Culture')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T006', 'Luxury')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T007', 'Food')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T008', 'Fitness')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T009', 'Art')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T010', 'Music')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T011', 'History')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T012', 'Nature')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T013', 'Wellness')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T014', 'Nightlife')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T015', 'Shopping')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T016', 'Sports')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T017', 'Photography')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T018', 'Festival')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T019', 'Social')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T020', 'Exploration')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T021', 'Learning')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T022', 'Health')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T023', 'Leisure')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T024', 'Thrill')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T025', 'Travel')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T026', 'Beach')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T027', 'Mountain')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T028', 'City')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T029', 'Yoga')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T030', 'Meditation')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T031', 'Wildlife')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T032', 'Camping')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T033', 'Road Trip')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T034', 'Water Sports')
    INTO Dg_Tags (Tag_ID, Tag_Name) VALUES ('T035', 'Cruise')
SELECT 1 FROM DUAL;

-- Inserting booking methods into the Dg_Booking_Methods table
INSERT ALL
    INTO Dg_Booking_Methods (Method_ID, Method_Name) VALUES ('BM001', 'Online')
    INTO Dg_Booking_Methods (Method_ID, Method_Name) VALUES ('BM002', 'Phone')
    INTO Dg_Booking_Methods (Method_ID, Method_Name) VALUES ('BM003', 'In-Person')
    INTO Dg_Booking_Methods (Method_ID, Method_Name) VALUES ('BM004', 'Travel Agent')
    INTO Dg_Booking_Methods (Method_ID, Method_Name) VALUES ('BM005', 'Mobile App')
SELECT 1 FROM DUAL;

-- Inserting booking statuses into the Dg_Booking_Status table
INSERT ALL
    INTO Dg_Booking_Status (Status_ID, Status_Name) VALUES ('BS001', 'Confirmed')
    INTO Dg_Booking_Status (Status_ID, Status_Name) VALUES ('BS002', 'Cancelled')
    INTO Dg_Booking_Status (Status_ID, Status_Name) VALUES ('BS003', 'Pending')
SELECT 1 FROM DUAL;

-- Inserting payment statuses into the Dg_Payment_Status table
INSERT ALL
    INTO Dg_Payment_Status (Payment_Status_ID, Payment_Status_Name) VALUES ('PS001', 'Pending')
    INTO Dg_Payment_Status (Payment_Status_ID, Payment_Status_Name) VALUES ('PS002', 'Completed')
    INTO Dg_Payment_Status (Payment_Status_ID, Payment_Status_Name) VALUES ('PS003', 'Failed')
    INTO Dg_Payment_Status (Payment_Status_ID, Payment_Status_Name) VALUES ('PS004', 'Refunded')
SELECT 1 FROM DUAL;

COMMIT;


